export const CREATE_NEW_BRANCH_REQUEST = "CREATE_NEW_BRANCH_REQUEST";
export const CREATE_NEW_BRANCH_SUCCESS = "CREATE_NEW_BRANCH_SUCCESS";
export const CREATE_NEW_BRANCH_FAILURE = "CREATE_NEW_BRANCH_FAILURE";
