export const GET_ALL_BRANCHES_REQUEST = "GET_ALL_BRANCHES_REQUEST";
export const GET_ALL_BRANCHES_SUCCESS = "GET_ALL_BRANCHES_SUCCESS";
export const GET_ALL_BRANCHES_FAILURE = "GET_ALL_BRANCHES_FAILURE";
