export const GET_BRANCH_BY_MA_CUM_RAP_REQUEST =
  "GET_BRANCH_BY_MA_CUM_RAP_REQUEST";
export const GET_BRANCH_BY_MA_CUM_RAP_SUCCESS =
  "GET_BRANCH_BY_MA_CUM_RAP_SUCCESS";
export const GET_BRANCH_BY_MA_CUM_RAP_FAILURE =
  "GET_BRANCH_BY_MA_CUM_RAP_FAILURE";
