export const CREATE_NEW_CAROUSEL_REQUEST = "CREATE_NEW_CAROUSEL_REQUEST";
export const CREATE_NEW_CAROUSEL_SUCCESS = "CREATE_NEW_CAROUSEL_SUCCESS";
export const CREATE_NEW_CAROUSEL_FAILURE = "CREATE_NEW_CAROUSEL_FAILURE";
