export const GET_CAROUSEL_BY_ID_REQUEST = "GET_CAROUSEL_BY_ID_REQUEST";
export const GET_CAROUSEL_BY_ID_SUCCESS = "GET_CAROUSEL_BY_ID_SUCCESS";
export const GET_CAROUSEL_BY_ID_FAILURE = "GET_CAROUSEL_BY_ID_FAILURE";
