export const CREATE_NEW_SCHEDULE_REQUEST = "CREATE_NEW_SCHEDULE_REQUEST";
export const CREATE_NEW_SCHEDULE_SUCCESS = "CREATE_NEW_SCHEDULE_SUCCESS";
export const CREATE_NEW_SCHEDULE_FAILURE = "CREATE_NEW_SCHEDULE_FAILURE";
