export const GET_ALL_SCHEDULES_FAILURE = "GET_ALL_SCHEDULES_FAILURE";
export const GET_ALL_SCHEDULES_REQUEST = "GET_ALL_SCHEDULES_REQUEST";
export const GET_ALL_SCHEDULES_SUCCESS = "GET_ALL_SCHEDULES_SUCCESS";
