export const CREATE_NEW_THEATER_REQUEST = "CREATE_NEW_THEATER_REQUEST";
export const CREATE_NEW_THEATER_SUCCESS = "CREATE_NEW_THEATER_SUCCESS";
export const CREATE_NEW_THEATER_FAILURE = "CREATE_NEW_THEATER_FAILURE";
