export const GET_THEATER_BY_MA_HE_THONG_RAP_REQUEST =
  "GET_THEATER_BY_MA_HE_THONG_RAP_REQUEST";
export const GET_THEATER_BY_MA_HE_THONG_RAP_SUCCESS =
  "GET_THEATER_BY_MA_HE_THONG_RAP_SUCCESS";
export const GET_THEATER_BY_MA_HE_THONG_RAP_FAILURE =
  "GET_THEATER_BY_MA_HE_THONG_RAP_FAILURE";
