export const CREATE_NEW_MOVIE_REQUEST = "CREATE_NEW_MOVIE_REQUEST";
export const CREATE_NEW_MOVIE_SUCCESS = "CREATE_NEW_MOVIE_SUCCESS";
export const CREATE_NEW_MOVIE_FAILURE = "CREATE_NEW_MOVIE_FAILURE";
